import { PhotoCategory } from '@/types';

export const PHOTO_CATEGORIES: PhotoCategory[] = [
  {
    id: 'model',
    title: 'Model Shooting',
    titleKo: '모델촬영',
    description: '디렉팅/스타일링/리터칭 작업내용',
    coverImage: '/images/photo/DSC07246.jpg',
    specs: [
      'SONY A9 FE 24-70mm F2.8 GM',
      '포맷 RAW',
      '리터칭 프로그램 Capture One',
      '자연광, 조명 촬영',
      '모델 포즈 디렉팅',
      '콘셉트 기획',
      '의상 및 헤어 스타일링 기획',
    ],
    images: [
      '/images/photo/DSC09490.jpg',
      '/images/photo/DSC02004.jpg',
      '/images/photo/DSC09752.jpg',
      '/images/photo/DSC09758.jpg',
      '/images/photo/DSC01175.jpg',
      '/images/photo/DSC00989.jpg',
      '/images/photo/GENUIO_1065.jpg',
      '/images/photo/GENUIO_0083.jpg',
      '/images/photo/DSC07633.jpg',
      '/images/photo/DSC07843.jpg',
      '/images/photo/GENUIO2813.jpg',
      '/images/photo/DSC01547.jpg',
      '/images/photo/GENUIO_0588.jpg',
      '/images/photo/GENUIO_1670.jpg',
      '/images/photo/DSC07120.jpg',
      '/images/photo/DSC08522.jpg',
      '/images/photo/GENUIO_0216.jpg',
      '/images/photo/GENUIO_0621.jpg',
      '/images/photo/GENUIO_1056.jpg',
      '/images/photo/GENUIO_1100.jpg',
      '/images/photo/GENUIO2721.jpg',
      '/images/photo/GENUIO2815.jpg',
    ],
  },
  {
    id: 'product',
    title: 'Product Shooting',
    titleKo: '제품촬영',
    description: '디렉팅/스타일링/리터칭 작업내용',
    coverImage: '/images/photo/cafe_menu_01.jpg',
    specs: [
      'SONY A9',
      'NIKON D3',
      'CANON 5D Mark3',
      '포맷 RAW',
      'Capture One',
      'Lightroom',
      '조명 촬영',
      '콘셉트 기획',
    ],
    images: [
      '/images/photo/genuio_product_01.jpg',
      '/images/photo/genuio_product_02.jpg',
      '/images/photo/genuio_product_03.jpg',
      '/images/photo/genuio_product_04.jpg',
      '/images/photo/genuio_product_05.jpg',
      '/images/photo/genuio_product_06.jpg',
      '/images/photo/genuio_product_07.jpg',
      '/images/photo/genuio_product_08.jpg',
      '/images/photo/genuio_product_09.jpg',
      '/images/photo/genuio_product_10.jpg',
      '/images/photo/genuio_product_11.jpg',
      '/images/photo/genuio_product_12.jpg',
      '/images/photo/genuio_product_13.jpg',
      '/images/photo/genuio_product_14.jpg',
      '/images/photo/genuio_product_15.jpg',
      '/images/photo/genuio_product_16.jpg',
      '/images/photo/cafe_menu_01.jpg',
      '/images/photo/cafe_menu_02.jpg',
      '/images/photo/cafe_menu_03.jpg',
      '/images/photo/cafe_menu_04.jpg',
      '/images/photo/esopoom_01.JPG',
      '/images/photo/esopoom_02.JPG',
      '/images/photo/esopoom_03.JPG',
      '/images/photo/esopoom_04.JPG',
    ],
  },
];
